In [22]:
import numpy as np

In [23]:
# 盘面转换为二维矩阵
# 状态1：黑色，已填充
# 状态0：白色，未填充

a = np.array([
    [0, 1, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 1, 1, 1, 0],
    [1, 1, 1, 1, 0, 1, 1, 1],
    [1, 1, 1, 0, 0, 1, 1, 0],
    [1, 1, 1, 1, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 1, 0, 0],
    [1, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 0, 0, 0, 0]
]
)

In [24]:
print(a.shape)

(8, 8)


In [25]:
print(a[1][3])

0


In [26]:
# 方块形状类型

# 对应横纵坐标，以左上角为原点，水平向右为x轴正方向，
# 竖直向下为y轴正方向，x对应横坐标，y对应纵坐标
SHAPES = {
    "1"  : [(0, 0)],
    "2"  : [(0, 0), (0, 1)],
    "3"  : [(0, 0), (1, 0)],
    "4"  : [(0, 0), (0, 1), (0, 2)],
    "5"  : [(0, 0), (1, 0), (2, 0)],
    "6"  : [(0, 0), (1, 0), (0, 1)],
    "7"  : [(0, 0), (0, 1), (0, 2), (0, 3)],
    "8"  : [(0, 0), (0, 1), (1, 1), (2, 1)],
    "9"  : [(0, 0), (1, 0), (0, 1), (1, 1)],
    "10" : [(1, 0), (0, 1), (1, 1), (2, 1)],
    "11" : [(0, 0), (1, 0), (2, 0), (3, 0), (4, 0)],
    "12" : [(0, 0), (1, 0), (2, 0), (2, 1), (2, 2)],
    "13" : [(0, 0), (1, 0), (2, 0), (0, 1), (1, 1), (2, 1), (0, 2), (1, 2), (2, 2)],
    "14" : [(1, 0), (2, 0), (0, 1), (1, 1)],
    "15" : [(0, 0), (1, 0), (1, 1)],
    "16" : [(0, 0), (0, 1), (1, 1), (1, 2)],
    "17" : [(0, 0), (1, 0), (2, 0), (3, 0)],
    "18" : [(0, 0), (1, 0), (1, 1), (2, 1)],
    "19" : [(1, 0), (0, 1), (1, 1), (0, 2)],
    "20" : [(0, 0), (0, 1), (1, 1), (0, 2)],
    "21" : [(0, 0), (1, 0), (2, 0), (0, 1), (0, 2)],
    "22" : [(0, 0), (0, 1), (0, 2), (0, 3), (0, 4)],
    "23" : [(0, 0), (0, 1), (0, 2), (1, 2), (2, 2)],
    "24" : [(2, 0), (2, 1), (0, 2), (1, 2), (2, 2)],
    "25" : [(1, 0), (0, 1), (1, 1), (1, 2)],
    "26" : [(0, 0), (1, 0), (2, 0), (1, 1)],
    "27" : [(0, 0), (0, 1), (1, 1)],
    "28" : [(1, 0), (0, 1), (1, 1)],
    "29" : [(1, 0), (1, 1), (0, 2), (1, 2)],
    "30" : [(0, 0), (1, 0), (2, 0), (2, 1)],
    "31" : [(0, 0), (1, 0), (0, 1), (0, 2)]
}

In [ ]:
# def check_row_complete(row):
#     for cell in row:
#         if cell=='':
#             return False

#     return True

In [27]:
i_block = list(SHAPES.keys())[9]
print(i_block)

10


In [28]:
print(SHAPES[i_block])

[(1, 0), (0, 1), (1, 1), (2, 1)]


In [29]:
max(max(SHAPES[i_block]))

2

In [30]:
b = SHAPES[i_block]

In [31]:
def trans_coordinate(b):
    xd = []
    yd = []
    for x, y in b:
        xd.append(x)
        yd.append(y)
    # print(xd)
    # print(yd)
    return max(xd)+1, max(yd)+1

x, y = trans_coordinate(b)
print(x)
print(y)

3
2


In [32]:
t = np.zeros((2,3), dtype=int)
print(t)

[[0 0 0]
 [0 0 0]]


In [33]:
for x, y in b:
    t[y][x] = 1
    
print(t)    

[[0 1 0]
 [1 1 1]]


In [34]:
t[:, :2]

array([[0, 1],
       [1, 1]])

In [43]:
t

array([[0, 1, 0],
       [1, 1, 1]])

In [46]:
t_zeros = np.ones_like(t)
t_zeros

array([[1, 1, 1],
       [1, 1, 1]])

In [47]:
temp = t + t_zeros
temp

array([[1, 2, 1],
       [2, 2, 2]])

In [57]:
temp.shape[0]

2

In [52]:
temp = np.where(temp<=1, True, False)
temp

array([[ True, False,  True],
       [False, False, False]])

In [55]:
np.all(temp)

False

In [35]:
t.shape[1]

3

In [36]:
a[1]

array([0, 0, 0, 0, 1, 1, 1, 0])

In [37]:
t[0]

array([0, 1, 0])

In [38]:
m = a[1]
# m[m == 0]
m

array([0, 0, 0, 0, 1, 1, 1, 0])

In [39]:
n = np.where(m == 0)

In [40]:
n[0]

array([0, 1, 2, 3, 7])

In [41]:
list(n[0])

[0, 1, 2, 3, 7]

In [42]:
for i in list(n[0]):
    print(i)

0
1
2
3
7


In [14]:
block = a
row = 8
col = 8

# generate 2D array with block shape
def generate_block(i):
    i_block = list(SHAPES.keys())[i]
    b = SHAPES[i_block]
    col, row = trans_coordinate(b)
    
    t = np.zeros((row, col), dtype=int)
    
    # x is col of array 
    # y is row of array 
    for x, y in b:  
        t[y][x] = 1
        
    return t

def indices_blank(a):
    """
    a: 1D row array
    return indices list of zero value  
    """
    n = np.where(a == 0)
    return list(n[0])
    
def check_putin(block, x):
    """
    block: generate block array
        x: the whole array
    """
    flag = False
    while flag == False:
        for r in range(x.shape[0]):  # rows
            id_blank = indices_blank(x[r])

            for i in id_blank:
                # temp = np.zeros_like(block)
                temp = block + x[i:i+block.shape[0], i:i+block.shape[1]]
                temp = np.where(temp<=1, True, False)
                # flag = np.all(temp)
                if np.all(temp):
                    flag = True
                    break
                    
        return flag
        
            
def check_clear():
    

SyntaxError: invalid syntax (1680232468.py, line 15)